UPDATE `game_members`
SET `icon_key` = CASE `icon_key`
  WHEN 'AliensByRegionHeads/RegionHead01_BrownDog.svg' THEN 'AliensByRegionHeads/Brown Dog.svg'
  WHEN 'AliensByRegionHeads/RegionHead02_BlueAlien.svg' THEN 'AliensByRegionHeads/Blue Alien.svg'
  WHEN 'AliensByRegionHeads/RegionHead03_GreyMask.svg' THEN 'AliensByRegionHeads/Grey Mask.svg'
  WHEN 'AliensByRegionHeads/RegionHead04_GreenAlienA.svg' THEN 'AliensByRegionHeads/Green Alien A.svg'
  WHEN 'AliensByRegionHeads/RegionHead05_GreenAlienB.svg' THEN 'AliensByRegionHeads/Green Alien B.svg'
  WHEN 'AliensByRegionHeads/RegionHead06_BraidedHuman.svg' THEN 'AliensByRegionHeads/Braided Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead07_IceElf.svg' THEN 'AliensByRegionHeads/Ice Elf.svg'
  WHEN 'AliensByRegionHeads/RegionHead08_WhiteCat.svg' THEN 'AliensByRegionHeads/White Cat.svg'
  WHEN 'AliensByRegionHeads/RegionHead09_OrangeCat.svg' THEN 'AliensByRegionHeads/Orange Cat.svg'
  WHEN 'AliensByRegionHeads/RegionHead10_GreyCat.svg' THEN 'AliensByRegionHeads/Grey Cat.svg'
  WHEN 'AliensByRegionHeads/RegionHead11_BlueHelmAlien.svg' THEN 'AliensByRegionHeads/Blue Helm Alien.svg'
  WHEN 'AliensByRegionHeads/RegionHead12_GreyFaceA.svg' THEN 'AliensByRegionHeads/Grey Face A.svg'
  WHEN 'AliensByRegionHeads/RegionHead13_GreyFaceB.svg' THEN 'AliensByRegionHeads/Grey Face B.svg'
  WHEN 'AliensByRegionHeads/RegionHead14_GreyFaceC.svg' THEN 'AliensByRegionHeads/Grey Face C.svg'
  WHEN 'AliensByRegionHeads/RegionHead15_Tiger.svg' THEN 'AliensByRegionHeads/Tiger.svg'
  WHEN 'AliensByRegionHeads/RegionHead16_CapHuman.svg' THEN 'AliensByRegionHeads/Cap Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead17_Astronaut.svg' THEN 'AliensByRegionHeads/Astronaut.svg'
  WHEN 'AliensByRegionHeads/RegionHead18_PinkPilot.svg' THEN 'AliensByRegionHeads/Pink Pilot.svg'
  WHEN 'AliensByRegionHeads/RegionHead19_SpottedDogA.svg' THEN 'AliensByRegionHeads/Spotted Dog A.svg'
  WHEN 'AliensByRegionHeads/RegionHead20_SpottedDogB.svg' THEN 'AliensByRegionHeads/Spotted Dog B.svg'
  WHEN 'AliensByRegionHeads/RegionHead21_GreenBug.svg' THEN 'AliensByRegionHeads/Green Bug.svg'
  WHEN 'AliensByRegionHeads/RegionHead22_BlueBug.svg' THEN 'AliensByRegionHeads/Blue Bug.svg'
  WHEN 'AliensByRegionHeads/RegionHead23_BlueBugSpotted.svg' THEN 'AliensByRegionHeads/Blue Bug Spotted.svg'
  WHEN 'AliensByRegionHeads/RegionHead24_BrownSnake.svg' THEN 'AliensByRegionHeads/Brown Snake.svg'
  WHEN 'AliensByRegionHeads/RegionHead25_OrangeSnake.svg' THEN 'AliensByRegionHeads/Orange Snake.svg'
  WHEN 'AliensByRegionHeads/RegionHead26_BlackSnake.svg' THEN 'AliensByRegionHeads/Black Snake.svg'
  WHEN 'AliensByRegionHeads/RegionHead27_GreenSnake.svg' THEN 'AliensByRegionHeads/Green Snake.svg'
  WHEN 'AliensByRegionHeads/RegionHead28_GreySplitFace.svg' THEN 'AliensByRegionHeads/Grey Split Face.svg'
  WHEN 'AliensByRegionHeads/RegionHead29_HalfRedFace.svg' THEN 'AliensByRegionHeads/Half Red Face.svg'
  WHEN 'AliensByRegionHeads/RegionHead30_BrownMask.svg' THEN 'AliensByRegionHeads/Brown Mask.svg'
  WHEN 'AliensByRegionHeads/RegionHead31_GreyHalfMask.svg' THEN 'AliensByRegionHeads/Grey Half Mask.svg'
  WHEN 'AliensByRegionHeads/RegionHead32_LilacCatA.svg' THEN 'AliensByRegionHeads/Lilac Cat A.svg'
  WHEN 'AliensByRegionHeads/RegionHead33_LilacCatB.svg' THEN 'AliensByRegionHeads/Lilac Cat B.svg'
  WHEN 'AliensByRegionHeads/RegionHead34_HornedGirlA.svg' THEN 'AliensByRegionHeads/Horned Girl A.svg'
  WHEN 'AliensByRegionHeads/RegionHead35_HornedGirlB.svg' THEN 'AliensByRegionHeads/Horned Girl B.svg'
  WHEN 'AliensByRegionHeads/RegionHead36_TealHelmAlien.svg' THEN 'AliensByRegionHeads/Teal Helm Alien.svg'
  WHEN 'AliensByRegionHeads/RegionHead37_NetHelmAlien.svg' THEN 'AliensByRegionHeads/Net Helm Alien.svg'
  WHEN 'AliensByRegionHeads/RegionHead38_GreenAlienSmile.svg' THEN 'AliensByRegionHeads/Green Alien Smile.svg'
  WHEN 'AliensByRegionHeads/RegionHead39_GreenAlienAngry.svg' THEN 'AliensByRegionHeads/Green Alien Angry.svg'
  WHEN 'AliensByRegionHeads/RegionHead40_GoldFace.svg' THEN 'AliensByRegionHeads/Gold Face.svg'
  WHEN 'AliensByRegionHeads/RegionHead41_CurlyHuman.svg' THEN 'AliensByRegionHeads/Curly Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead42_BlackHairHuman.svg' THEN 'AliensByRegionHeads/Black Hair Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead43_Angel.svg' THEN 'AliensByRegionHeads/Angel.svg'
  WHEN 'AliensByRegionHeads/RegionHead44_HornedGirlC.svg' THEN 'AliensByRegionHeads/Horned Girl C.svg'
  WHEN 'AliensByRegionHeads/RegionHead45_GreenOgreHairA.svg' THEN 'AliensByRegionHeads/Green Ogre Hair A.svg'
  WHEN 'AliensByRegionHeads/RegionHead46_GreenOgreCapA.svg' THEN 'AliensByRegionHeads/Green Ogre Cap A.svg'
  WHEN 'AliensByRegionHeads/RegionHead47_GreenOgreCapB.svg' THEN 'AliensByRegionHeads/Green Ogre Cap B.svg'
  WHEN 'AliensByRegionHeads/RegionHead48_GreenOgreCapC.svg' THEN 'AliensByRegionHeads/Green Ogre Cap C.svg'
  WHEN 'AliensByRegionHeads/RegionHead49_GreenOgreHairB.svg' THEN 'AliensByRegionHeads/Green Ogre Hair B.svg'
  WHEN 'AliensByRegionHeads/RegionHead50_BlueBugFullA.svg' THEN 'AliensByRegionHeads/Blue Bug Full A.svg'
  WHEN 'AliensByRegionHeads/RegionHead51_GreenBugFullA.svg' THEN 'AliensByRegionHeads/Green Bug Full A.svg'
  WHEN 'AliensByRegionHeads/RegionHead52_BlueBugFullB.svg' THEN 'AliensByRegionHeads/Blue Bug Full B.svg'
  WHEN 'AliensByRegionHeads/RegionHead53_GreenBugFullB.svg' THEN 'AliensByRegionHeads/Green Bug Full B.svg'
  WHEN 'AliensByRegionHeads/RegionHead54_GreenOgreHairC.svg' THEN 'AliensByRegionHeads/Green Ogre Hair C.svg'
  WHEN 'AliensByRegionHeads/RegionHead55_GreenOgreHairD.svg' THEN 'AliensByRegionHeads/Green Ogre Hair D.svg'
  WHEN 'AliensByRegionHeads/RegionHead56_GreenOgreHairE.svg' THEN 'AliensByRegionHeads/Green Ogre Hair E.svg'
  WHEN 'AliensByRegionHeads/RegionHead57_WhiteLionA.svg' THEN 'AliensByRegionHeads/White Lion A.svg'
  WHEN 'AliensByRegionHeads/RegionHead58_BrownLionA.svg' THEN 'AliensByRegionHeads/Brown Lion A.svg'
  WHEN 'AliensByRegionHeads/RegionHead59_PaleLionA.svg' THEN 'AliensByRegionHeads/Pale Lion A.svg'
  WHEN 'AliensByRegionHeads/RegionHead60_WhiteLionB.svg' THEN 'AliensByRegionHeads/White Lion B.svg'
  WHEN 'AliensByRegionHeads/RegionHead61_SpikyHuman.svg' THEN 'AliensByRegionHeads/Spiky Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead62_BrownLionB.svg' THEN 'AliensByRegionHeads/Brown Lion B.svg'
  WHEN 'AliensByRegionHeads/RegionHead63_PaleLionB.svg' THEN 'AliensByRegionHeads/Pale Lion B.svg'
  WHEN 'AliensByRegionHeads/RegionHead64_BlackCat.svg' THEN 'AliensByRegionHeads/Black Cat.svg'
  WHEN 'AliensByRegionHeads/RegionHead65_GreenBugFullC.svg' THEN 'AliensByRegionHeads/Green Bug Full C.svg'
  WHEN 'AliensByRegionHeads/RegionHead66_GreenBugSpottedFull.svg' THEN 'AliensByRegionHeads/Green Bug Spotted Full.svg'
  WHEN 'AliensByRegionHeads/RegionHead67_BrownDogB.svg' THEN 'AliensByRegionHeads/Brown Dog B.svg'
  WHEN 'AliensByRegionHeads/RegionHead68_HornedGirlD.svg' THEN 'AliensByRegionHeads/Horned Girl D.svg'
  WHEN 'AliensByRegionHeads/RegionHead69_BeardedHuman.svg' THEN 'AliensByRegionHeads/Bearded Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead70_HornedGirlE.svg' THEN 'AliensByRegionHeads/Horned Girl E.svg'
  WHEN 'AliensByRegionHeads/RegionHead71_HornedGirlF.svg' THEN 'AliensByRegionHeads/Horned Girl F.svg'
  WHEN 'AliensByRegionHeads/RegionHead72_PaleHumanA.svg' THEN 'AliensByRegionHeads/Pale Human A.svg'
  WHEN 'AliensByRegionHeads/RegionHead73_BowlCutHumanA.svg' THEN 'AliensByRegionHeads/Bowl Cut Human A.svg'
  WHEN 'AliensByRegionHeads/RegionHead74_BowlCutHumanB.svg' THEN 'AliensByRegionHeads/Bowl Cut Human B.svg'
  WHEN 'AliensByRegionHeads/RegionHead75_BowlCutHumanC.svg' THEN 'AliensByRegionHeads/Bowl Cut Human C.svg'
  WHEN 'AliensByRegionHeads/RegionHead76_BowlCutHumanD.svg' THEN 'AliensByRegionHeads/Bowl Cut Human D.svg'
  WHEN 'AliensByRegionHeads/RegionHead77_BlondeBraidsHuman.svg' THEN 'AliensByRegionHeads/Blonde Braids Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead78_BeanieHuman.svg' THEN 'AliensByRegionHeads/Beanie Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead79_RecedingHairHuman.svg' THEN 'AliensByRegionHeads/Receding Hair Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead80_DarkHumanA.svg' THEN 'AliensByRegionHeads/Dark Human A.svg'
  WHEN 'AliensByRegionHeads/RegionHead81_GoateeHuman.svg' THEN 'AliensByRegionHeads/Goatee Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead82_DarkHumanB.svg' THEN 'AliensByRegionHeads/Dark Human B.svg'
  WHEN 'AliensByRegionHeads/RegionHead83_BlondeHuman.svg' THEN 'AliensByRegionHeads/Blonde Human.svg'
  WHEN 'AliensByRegionHeads/RegionHead84_TongueAlienWhite.svg' THEN 'AliensByRegionHeads/Tongue Alien White.svg'
  WHEN 'AliensByRegionHeads/RegionHead85_TongueAlienGold.svg' THEN 'AliensByRegionHeads/Tongue Alien Gold.svg'
  WHEN 'AliensByRegionHeads/RegionHead86_RedAstronautAlien.svg' THEN 'AliensByRegionHeads/Red Astronaut Alien.svg'
  WHEN 'AliensByRegionHeads/RegionHead87_TealHelmAlienB.svg' THEN 'AliensByRegionHeads/Teal Helm Alien B.svg'
  WHEN 'AliensByRegionHeads/RegionHead88_BlueBugSpottedB.svg' THEN 'AliensByRegionHeads/Blue Bug Spotted B.svg'
  WHEN 'AliensByRegionHeads/RegionHead89_BlueBugPlainB.svg' THEN 'AliensByRegionHeads/Blue Bug Plain B.svg'
  WHEN 'AliensByRegionHeads/RegionHead90_GreenBugPlainB.svg' THEN 'AliensByRegionHeads/Green Bug Plain B.svg'
  WHEN 'AliensByRegionHeads/RegionHead91_BlueBugFullC.svg' THEN 'AliensByRegionHeads/Blue Bug Full C.svg'
  WHEN 'AliensByRegionHeads/RegionHead92_BlueBugFullD.svg' THEN 'AliensByRegionHeads/Blue Bug Full D.svg'
  WHEN 'AliensByRegionHeads/RegionHead93_GreenBugFullD.svg' THEN 'AliensByRegionHeads/Green Bug Full D.svg'
  WHEN 'AliensByRegionHeads/RegionHead94_GreenOgreHairF.svg' THEN 'AliensByRegionHeads/Green Ogre Hair F.svg'
  WHEN 'AliensByRegionHeads/RegionHead95_GreenOgreFaceA.svg' THEN 'AliensByRegionHeads/Green Ogre Face A.svg'
  WHEN 'AliensByRegionHeads/RegionHead96_GoldFaceB.svg' THEN 'AliensByRegionHeads/Gold Face B.svg'
  WHEN 'AliensByRegionHeads/RegionHead97_BronzeFaceA.svg' THEN 'AliensByRegionHeads/Bronze Face A.svg'
  WHEN 'AliensByRegionHeads/RegionHead98_WhiteFaceA.svg' THEN 'AliensByRegionHeads/White Face A.svg'
  WHEN 'AliensByRegionHeads/RegionHead99_GreenElfA.svg' THEN 'AliensByRegionHeads/Green Elf A.svg'
  WHEN 'AliensByRegionHeads/RegionHead100_IceElfB.svg' THEN 'AliensByRegionHeads/Ice Elf B.svg'
  WHEN 'AliensByRegionHeads/RegionHead101_AmberElfA.svg' THEN 'AliensByRegionHeads/Amber Elf A.svg'
  WHEN 'AliensByRegionHeads/RegionHead102_PaleElfA.svg' THEN 'AliensByRegionHeads/Pale Elf A.svg'
  WHEN 'AliensByRegionHeads/RegionHead103_TongueAlienBlack.svg' THEN 'AliensByRegionHeads/Tongue Alien Black.svg'
  WHEN 'AliensByRegionHeads/RegionHead104_GreenBugPlainC.svg' THEN 'AliensByRegionHeads/Green Bug Plain C.svg'
  WHEN 'AliensByRegionHeads/RegionHead105_GreenBugFullE.svg' THEN 'AliensByRegionHeads/Green Bug Full E.svg'
  WHEN 'AliensByRegionHeads/RegionHead106_GreenBugSpottedB.svg' THEN 'AliensByRegionHeads/Green Bug Spotted B.svg'
  WHEN 'AliensByRegionHeads/RegionHead107_TealHelmAlienC.svg' THEN 'AliensByRegionHeads/Teal Helm Alien C.svg'
  WHEN 'AliensByRegionHeads/RegionHead108_GreenBugPlainD.svg' THEN 'AliensByRegionHeads/Green Bug Plain D.svg'
  WHEN 'AliensByRegionHeads/RegionHead109_GreenBugSpottedFullB.svg' THEN 'AliensByRegionHeads/Green Bug Spotted Full B.svg'
  ELSE `icon_key`
END
WHERE `icon_key` LIKE 'AliensByRegionHeads/RegionHead%.svg';